// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type User struct {
	ID                       int32
	Username                 string
	Email                    string
	Password                 string
	FirstName                string
	LastName                 string
	CreatedAt                sql.NullTime
	UpdatedAt                sql.NullTime
	Verified                 sql.NullBool
	ResetPasswordToken       sql.NullString
	ResetPasswordTokenSentAt sql.NullTime
}
