# syntax=docker/dockerfile:1

FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /go-auth

FROM builder AS run-test-image

# Deploy the application binary into a lean container
FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=builder /go-auth /app

EXPOSE 8000

ENTRYPOINT ["app"]
