version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go-auth
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/go-auth?sslmode=disable
    depends_on:
      - db
    ports:
      - "8080:8080"

